### ISSUE TITLE
Version 0.3.0 wil not install.

### ISSUE THREAD

**Issue by KCarterSr** [OJacot-Descombes/PrettyDocComments#1]
I just tried it. Version 0.3.0 will not install. It just say's already installed.

I'm on 0.2.8

I tried uninstalling then reinstalling.

Thanks

**Comment by OJacot-Descombes** [comment]
I hope it was a sporadic problem. It installed without problems on my system.

- Did uninstall / re-install work?
- Did someone else have a problem updating it?

I just bump up the version number to 0.3.1, hope it helps.

**Comment by KCarterSr** [comment]
That bump up fixed the problem.

Thanks
