### ISSUE TITLE
Allow  To Set The Font Family.

### ISSUE THREAD

**Issue by yekanchi** [OJacot-Descombes/PrettyDocComments#2]
Currently there is no option to set the font family.
Is it possible to let the font to be chosen in options?

**Comment by OJacot-Descombes** [comment]
Just added it in version 0.3.2.
You can select the normal text font and the code text font in the Options page.
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/c4f3bb8c-dc16-40b9-8adf-1eeaf3fe43da)
