### ISSUE TITLE
Visible whitespace is shown on top of rendered images

### ISSUE THREAD

**Issue by gix** [OJacot-Descombes/PrettyDocComments#3]
The layer at which the rendered images are placed is below that of visible whitespace (Edit -> Advanced -> View White Space). When enabled, those whitespace indicators are visible over the text:

![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/51795/f87b1d87-bdd2-42c5-ba4f-ed7483d6f799)

**Comment by OJacot-Descombes** [comment]
Fixed in version 0.3.4
