### ISSUE TITLE
Feature: Collapsed view

### ISSUE THREAD

**Issue by wekempf** [OJacot-Descombes/PrettyDocComments#5]
Absolutely awesome extension. Provides a much nicer display of documentation comments, which normally absolutely obscures the code. I'd like to make another suggestion to even further help bring focus back to the code. Collapse the comment view down to show just the summary. Here's how I'd envision this working.

1. This feature would be entirely controlled via configuration. Default could even be to behave as it does today.
2. When enabled the following behavior would be observed.
    1. A key binding would allow you to toggle between collapsed view and full view for the entire file.
    2. When in collapsed view all comments would be collapsed to show just the summary text, with a visual cue that it can be expanded.
    3. When the cursor is within a method, that method's comment would be expanded.

This should make it easy to see the full documentation "on demand" while giving a very nice and clean summary view normally.

**Comment by OJacot-Descombes** [comment]
Thank you for the suggestion. I am not sure if it is a good idea to change the collapse (also called outline) behavior. Currently it is controlled by Visual Studio. But maybe I could add a toolbar or key command to switch between full comment view and summary-only view (for all comments).

The collapsing behavior of VS would not change.

What do you think?

**Comment by OJacot-Descombes** [comment]
Or maybe I could integrate a button in the comment (on the thick separator line after the summary) if something follows the summary.

**Comment by wekempf** [comment]
I'm not sure what you mean by the "collapse (also called outline) behavior" in Visual Studio. Sounds like you're referring to code folding? That's about a lot more than comments. You could make this idea work in conjunction with this, but that sounds a bit complicated. Code folding is all about letting you focus on the API, while this idea is about letting you focus on the code.

Expanded view.

![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/3430823/13f36307-5038-4278-ac87-c74acff7d4f9)

Collapsed (possibly default) view.

![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/3430823/fc4aa4d5-27c8-4a98-9c06-e572fe029f22)

I obviously cheated and just removed everything but the summary in the underlying comment to produce that image. In the actual implementation there'd be a visual cue of some sort, like an ellipses displayed on the right side of a collapsed view.

Note that only the "pretty comment" UI is collapsed... all of the source code remains as normal. For code folding, I'd suggest this should ignore whether or not the code is folded. When the UI is hidden, the code will be folded or unfolded based on what the user has done, not based on the collapsed/expanded state of the "pretty comment" UI.

Again, the idea is to make it easy to focus on the code. Summaries remain, because they's short, non-distracting and provide "just enough" information when viewing the code, and expand when in a type/member definition to show everything when modifying the code. On those occasions you want to see it all, you can expand all the pretty comments, and if you're really focused on the documentation you can even fold all the code and expand the pretty comments.

Oh, and a button on the comment might be OK for individual comments and would give you that visual cue, but to really be useful you need to be able to expand/collapse all of them quickly, and I'd still like the "expand while editing the associated type/member" automatic behavior.

**Comment by OJacot-Descombes** [comment]
I was a little bit confused and thought you were talking about the text folding [+]. Sorry for that.

The intention of the button is to act on all the comments. Placing it in the comment has the advantage that we don't need a menu or toolbar entry or key binding.

Possible placement (not definitive look):
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/88b67f6b-3749-4e7e-806e-a71b1a4db44a)

![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/18df9a62-a179-499c-afe9-20765fe1c880)

**Comment by wekempf** [comment]
Yes, but to be really useful I *want* the key binding to expand collapse *all* the pretty comments in the file. The button is fine, but complicates things as you have to track state on individual comments. That's fine, and I can see lots of folks appreciating that, but I don't really think it's necessary. When the comment expands automatically when you're within the member/type there's less need for it. It really only allows you to make the state "sticky",  until the next action would change the state. It does give you the visual cue, though, and I'm fine with it, I just want to ask that the rest of the behavior I described isn't lost by adding the button. I want expand/collapse key bindings/toolbar buttons that expand/collapse the entire file. I want the behavior to either be collapsed by default, or configurable if you think most users would prefer expanded by default.

**Edit**: Just read "the intention of the button is to act on all the comments". Not sure that's intuitive UX, but would mean you're not tracking state for individual comments. I'd still really like the selected type/member to have its comment expanded regardless, but that all works with the buttons being "for all comments" by some definition of "all". :)

**Comment by wekempf** [comment]
Trying to describe the behavior a little more clearly.

1. A configuration option controls whether expanding/collapsing is desirable. If it's off, comments always remain expanded and the following does not apply.
2. When I file is first opened the comments are all collapsed.
2. As selection moves into a type/member the associated doc comment is expanded.
3. As selection moves out of a type/member the associated doc comment is collapsed.
4. A command (key binding/toolbar button) changes behavior the same as the configuration option does toggling between everything being expanded all the time (within the file, not globally) and being expanded/collapsed based on the above.
5. If a button is included on the comment it should either behave the same as the toggle command, or should toggle the state of that individual comment until one of the above would change the state again. (Good UX means there should be a separate key binding for toggling individual comments in this case.)

**Comment by OJacot-Descombes** [comment]
The comments overlay image is only created for the comments inside the view-port. Also they are dismissed after each edit or scroll operation and are re-created from scratch. I.e., they are state-less. This means that I have no place to store individual expanded/collapse state.

This extension is not based on the compiler's syntax analysis but only detects `///` (or `'''` for VB). This allows me to support C#, C++, F# and VB. But this also means that I don't have any information about types and members. Auto expand/collapse is therefore not possible (at least not in this way). Maybe expand by hovering over the image? But I fear that it would be very distracting if comments collapse and expand all the time. Maybe a time delay would help.

Note also that if you collapse the comment with VS' text-folding and you hover over a member, then a tool-tip with the summary and additional member information will be will be displayed. So there is a lot of overlap between this new feature and what VS already does.

**Comment by wekempf** [comment]
I don't expect state persistence beyond that, honestly. You'd have a single value to track: are the comments expanded or collapsed. That's global state, initially set by configuration and modified by the command/key binding.

The no syntax analysis would make it a little harder to expand when inside a member. Just being able to expand/collapse globally would suffice, as far as I'm concerned. But you could do less work and approximate the expansion behavior... the comment closest to the cursor from above would be expanded. Not precise, but close enough. The distraction might be something that some would have problems with, still. Expanding when the mouse is over would be a compromise, but I'm a "stay on the keyboard as much as you can" type, so would rarely use the mouse for this purpose. I'd rather use the key binding. But that's a personal preference thing.

As stated, code folding serves a different purpose and is too awkward for this usage, but yes, I do understand the overlap.

**Comment by wekempf** [comment]
BTW, I'm not going to stop using this extension if this feature isn't implemented. If you like the idea of the feature and just don't have time to implement it, I could also take a crack at creating a PR for it, though my time is limited as well. IOW, I would love to have this feature, but you shouldn't feel pressured by some random dude to do it. :)

**Comment by OJacot-Descombes** [comment]
Thank you for the input. Time is not the problem as I am retired. A new feature must integrate technically with the current implementation and must feel natural and be easy in usage. So I prefer to spend some time thinking about it.

Btw., the state thing was about hiding/collapsing individual comments. I prefer a global approach.

**Comment by OJacot-Descombes** [comment]
Implemented (at least partially) in version 0.4.0

The collapse state can be toggled through the **Options dialog**, the menu **Edit > Toggle Collapse Comments to Summary** and through a **key shortcut** that you must assign yourself to the command **Edit.ToggleCollapseCommentstoSummary**.

No auto-expand was implemented.

**Comment by wekempf** [comment]
Perfect! Thank you.
