### ISSUE TITLE
Exception when there is `&` charachter inside

### ISSUE THREAD

**Issue by yekanchi** [OJacot-Descombes/PrettyDocComments#7]
the extension does not work and show red border when there is `&` character inside summary text.

**Comment by OJacot-Descombes** [comment]
Because an `&` is not a valid XML character. You must escape it with `&amp;`.

**Comment by yekanchi** [comment]
> Because an `&` is not a valid XML character. You must escape it with `&amp;`.

is it possible to replace it before parsing? because some people tend to use it in the comments.
Actually, we cannot avoid it I think.

**Comment by OJacot-Descombes** [comment]
It is not only the pretty doc comment that does not work. Also Visual Studio's IntelliSense does not work if the XML is not valid. In XML the ampersand introduces escapes like `&lt;` for `<`. This is why the ampersand itself must be escaped. Note that this applies only for doc-comments, not for the normal comments.

Note that the extension shows red borders and displays an error message **intentionally**! 

Example with XML error and Visual Studio's IntelliSense not showing the summary:
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/40d7b21f-1044-42b3-bc6e-ca09b5e8ad47)

Example with error fixed (i.e., `&` replaced by `&amp;` in the comment) and IntelliSense now showing the summary:
![image](https://github.com/OJacot-Descombes/PrettyDocComments/assets/12754787/f29177a3-618f-4cc3-8873-7a115c0b4097)
